### ISSUE TITLE
Tapped formula crashes during install

### ISSUE THREAD

**Issue by michaelblyons** [decors/homebrew-cipherscan#1]
Something seems to be screwy about the `ecdsa` python resource.

```
$ brew install --HEAD --debug cipherscan
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/decors/homebrew-cipherscan/Formula/cipherscan.rb
==> Installing cipherscan from decors/cipherscan
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/decors/homebrew-cipherscan/Formula/cipherscan.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/mozilla/cipherscan.git
Updating /Users/.../Library/Caches/Homebrew/cipherscan--git
==> Checking out branch master
==> Patching
patching file cipherscan
Hunk #2 succeeded at 2104 (offset 3 lines).
patching file cscan.sh
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:284:in `initialize'
Errno::ENOENT: No such file or directory - /Users/.../Library/Caches/Homebrew/cipherscan--ecdsa-0.13.tar.gz
1. raise
2. backtrace
3. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/cipherscan-20170705-56080-15vk7p4
Error: No such file or directory - /Users/.../Library/Caches/Homebrew/cipherscan--ecdsa-0.13.tar.gz
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:284:in `initialize'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:284:in `open'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:284:in `open'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:284:in `compression_type'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:224:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Taps/decors/homebrew-cipherscan/Formula/cipherscan.rb:24:in `block in install'
/usr/local/Homebrew/Library/Taps/decors/homebrew-cipherscan/Formula/cipherscan.rb:23:in `each'
/usr/local/Homebrew/Library/Taps/decors/homebrew-cipherscan/Formula/cipherscan.rb:23:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:92:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:137:in `block in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by michaelblyons** [comment]
@decors Thank you!
